### ISSUE TITLE
Finish Command Line parser

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-stix-elevator#10]
Some options are already implemented via a Boolean flag:

- retain the STIX 2.0 observed data object, even if the purpose of the STIX1.x observable was to specify an indicator pattern 
- include STIX 1.x content that cannot be represented directly in STIX 2.0 in the description property
- use Incident and Infrastructure stubs that weren’t included in 2.0

Some other ones we may want to implement:

- turn on or off certain errors or warnings 
- default identity for created_by_ref 
- default timestamp 
- how to handle CybOX 2.0 objects in STIX 1.x patterns that cannot be represented in STIX 2.0

**Comment by gtback** [comment]
Some values (like the "default" values above) could work as global configuration variables.

**Comment by gtback** [comment]
This may involve creating a single structure to hold all configuration values.

**Comment by rpiazza** [comment]
Should the default created_by_identity be generated as an object?

**Comment by gtback** [comment]
I'm not sure what you mean, @rpiazza. Do you mean creating (and including) an Identity object rather than just a reference? 

If so, that's possibly a good idea, but I don't know where you would get values from. If I remember correctly, my thinking when I created this issue was that the user might know they had an Identity object representing themselves somewhere that had already been defined, and by providing this idref we could include it on all objects the Elevator creates.

**Comment by rpiazza** [comment]
Yes - that was idea - but I just entered the comment to note the question somewhere :-)

**Comment by gtback** [comment]
Sounds good, thanks!

**Comment by emmanvg** [comment]
Are there any other requests for this issue?

**Comment by rpiazza** [comment]
Let's close this issue.  If we determine there is more to do, open a new issue
