### ISSUE TITLE
Handle Composite Indicator Expression

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-stix-elevator#11]
This feature is not in STIX 2.0 as it was in STIX 1.x. Need to figure out how to compensate for this.

**Comment by rpiazza** [comment]
Currently treating composite indicators in the same way composite observables

see https://github.com/oasis-open/cti-stix-elevator/commit/d3e5a327bb260f4735542798c6dc644bfe500d1e  thru https://github.com/oasis-open/cti-stix-elevator/commit/8519de6a817df0f889c3674e03e4677ce116465b
