### ISSUE TITLE
Unable to silence logging.

### ISSUE THREAD

**Issue by tigerkatz** [oasis-open/cti-stix-elevator#113]
I am trying to silence the logging for the elevator with set_option_value('silent', True). But it is not working. 

When I use the below code to test the values, test_val shows "silent" as true, but opts["silent"] comes back as false, and everything gets logged out anyways.

            initialize_options()
            set_option_value('silent', True)
            test_val = get_option_value('silent')
            opts = get_validator_options()
            elevated = elevate_string(xml_str_sent)

Thank you

**Comment by rpiazza** [comment]
@tigerkatz, the integration between the elevator options and validator options are not as coordinated as is optimal.  In your code, you set the elevator option to silent, but this does not set the validator option to be silent.  The easiest way to handle this would be add the following code:

set_option_value('validator-args', '--silent')

**Comment by tigerkatz** [comment]
Thanks, I added your line of code and that did the trick.

            set_option_value('validator_args', '--silent')
            set_option_value('silent', 'True')

Thank you.
