### ISSUE TITLE
Remove code in convert_network_connection which converts DNS queries

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-elevator#120]
There is code that added two objects to the observed-data's objects (an address and domain_name) for each DNS query result, but they are not referred to by any other object, and the really aren't STIX 1.x "related" objects.

**Comment by emmanvg** [comment]
@rpiazza, can you expand on what is the issue and the offending code that is causing this?

**Comment by emmanvg** [comment]
As far as I recall, the network connection code is based on this input and this is the output: 

- https://github.com/oasis-open/cti-stix-elevator/blob/master/idioms-xml/observable-with-networkconnection-instance.xml
- https://github.com/oasis-open/cti-stix-elevator/blob/master/idioms-json/observable-with-networkconnection-instance.json

**Comment by rpiazza** [comment]
The code from line 473 in convert_cybox.py handles dns_query results.  We don't represent dns_queries in STIX 2.0.  This looks like a possible solution, but Ivan and I discussed it and thought that it is misleading and possibly confusing, so we thought it should be removed.  As far as I know, we don't have any examples that make use of this code.
