### ISSUE TITLE
Support Data Markings

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-stix-elevator#13]

**Comment by gtback** [comment]
Need to figure out how to address AIS markings.

**Comment by emmanvg** [comment]
Handling Field Level markings with is a very complex task... I could hit for supporting global markings (//node() | //@*) and TLO Markings (../../../descendant-or-self::node() | ../../../descendant-or-self::node()/@*) Does that sound reasonable?

**Comment by gtback** [comment]
I don't think we should worry about field-level markings (probably at all, but certainly for now). As long as we can convert AIS content and markings, that should be a good start.

**Comment by emmanvg** [comment]
PR #54 also has support for AISMarkingStructure, TLPMarkingStructure, SimpleMarkingStructure and TOUMarkingStructure.

**Comment by emmanvg** [comment]
Can we close this issue?

**Comment by gtback** [comment]
Yep! Fixed by #54

**Comment by rpiazza** [comment]
I didn't close it because we are still working on one of the messages :-)
