### ISSUE TITLE
ISAMarkingType Support

### ISSUE THREAD

**Issue by hanymorcos** [oasis-open/cti-stix-elevator#132]
Stix2 Elevator doesn't include support for ISA Marking Type.  After including STIX-edh in setup.py and doing an import stix-edh in convert_stix.py, the XML was loaded but it was still failing in STIX Elevator. 

Before including stix-edh:
NotImplementedError: No class implemented or registered for XML type '{http://www.us-cert.gov/sites/default/files/STIX_Namespace/ISAMarkingsType.v2.xsd}ISAMarkingsType'
--

After including stix-edh:
  File "/usr/local/lib/python2.7/site-packages/stix2elevator/convert_stix.py", line 261, in convert_marking_specification
    raise NameError("Could not resolve Marking Structure %s" % identifying_info(mark_spec))

**Comment by rpiazza** [comment]
Hi @hanymorcos.  Thanks for opening this issue!  Sorry, with the holidays, it fell thru the cracks.  

It is true, that the elevator does not handle IAS markings.  However, there is an option that you can pass to the elevator that will avoid the exception and just give you a warning.  see the "markings-allowed" option.  The example in the documentation is probably what you need.

I'm going to close this issue, please reopen it if this workaround doesn't work for you.

**Comment by hanymorcos** [comment]
Is that something that you would support in the next release?
Thanks,

Hany

**Comment by rpiazza** [comment]
@hanymorcos - Working with DHS, we have developed a new schema of IAS for STIX 2.x.  If that is adopted, we may handle IAS in the elevator.
