### ISSUE TITLE
STIX-CIQ tags are converted to a Location type

### ISSUE THREAD

**Issue by hanymorcos** [oasis-open/cti-stix-elevator#134]
Location is not a valid STIX 2.X type. STIX-CIQ XML Tag (http://stix.mitre.org/extensions/Identity#CIQIdentity3.0-1) address is converted to a location type. Location type is failing STIX 2 validation.

          <stixCommon:Identity xsi:type="stix-ciq:CIQIdentity3.0InstanceType">
            <stix-ciq:Specification>
              <xpil:PartyName>
                <xnl:OrganisationName>
                  <xnl:NameElement>ACME</xnl:NameElement>
                </xnl:OrganisationName>
              </xpil:PartyName>
              <xpil:Addresses>
                <xpil:Address>
                  <xal:Country>
                    <xal:NameElement xal:NameCode="US" xal:NameCodeType="ISO 3166-1 alpha-2" />
                  </xal:Country>
                  <xal:AdministrativeArea>
                    <xal:NameElement xal:NameCode="US-NY" xal:NameCodeType="ISO 3166-2" />
                  </xal:AdministrativeArea>
                </xpil:Address>
              </xpil:Addresses>
              <xpil:OrganisationInfo xpil:IndustryType="Transportation Systems Sector" />
            </stix-ciq:Specification>
          </stixCommon:Identity>

**Comment by rpiazza** [comment]
Hi @hanymorcos,

Yes - the validator is a little behind in development vs the elevator.  A new release of the stix2 validator will be out very soon and will handle both v2.0 and v2.1

**Comment by hanymorcos** [comment]
Thanks.
