### ISSUE TITLE
Name/indicator_types required property 

### ISSUE THREAD

**Issue by hanymorcos** [oasis-open/cti-stix-elevator#136]
I'm getting error from JSON Validator because some of these attributes are missing. 

Name is a required property in attack-pattern STIX 2.1
Name is a required property in vulnerability STIX 2.1
Labels are renamed to indicator_types in STIX 2.1 and they are required

**Comment by clenk** [comment]
Hi @hanymorcos. This is really an issue for the [stix validator](https://github.com/oasis-open/cti-stix-validator), not the elevator. The validator does not yet support 2.1 but we are working on it and it will very soon.

**Comment by hanymorcos** [comment]
The validator I believe currently supports 2.1. It's still an issue in current release.
