### ISSUE TITLE
Prefix unconverted_term added to indicator type 

### ISSUE THREAD

**Issue by hanymorcos** [oasis-open/cti-stix-elevator#148]
It seems indicator is failing to cross reference Observable already defined in the same STIX file. 

<stix:Observables cybox_major_version="2" cybox_minor_version="1">
    <cybox:Observable id="NCCIC:Observable-d2be7dd8-0b0c-4c76-8bc0-20c93718941c">
      <cybox:Object id="NCCIC:Port-8e770243-59e4-42a8-9c58-2f5d1b12bc65">
		<cybox:Properties xsi:type="PortObj:PortObjectType">
		  <PortObj:Port_Value condition="Equals">337</PortObj:Port_Value>
		  <PortObj:Layer4_Protocol condition="Equals">DCCP</PortObj:Layer4_Protocol>
		</cybox:Properties>
	  </cybox:Object>
    </cybox:Observable>
  </stix:Observables>
  <stix:Indicators>
    <stix:Indicator id="NCCIC:Indicator-b61d71d8-fe37-4bcd-a76d-d437156b8226" version="2.0" xsi:type="indicator:IndicatorType">
      <indicator:Title>Incident on Port</indicator:Title>
	  <indicator:Type>Anonymization</indicator:Type>
      <indicator:Description>Port Numbers</indicator:Description>
      <indicator:Observable idref="NCCIC:Observable-d2be7dd8-0b0c-4c76-8bc0-20c93718941c"/>
    </stix:Indicator>
  </stix:Indicators>

Generated JSON and validation error. 

[X] STIX JSON: Invalid
    [X] indicator--b61d71d8-fe37-4bcd-a76d-d437156b8226: Pattern failed to validate: FAIL: Error found at line 1:23. no viable alternative at input 'unconverted_term:NCCIC:'.
{
    "id": "bundle--e693f1af-acf2-415c-8729-6c1aff025265",
    "objects": [
        {
            "created": "9999-12-31T00:00:00.000Z",
            "description": "Port Numbers",
            "id": "indicator--b61d71d8-fe37-4bcd-a76d-d437156b8226",
            "indicator_types": [
                "anonymization"
            ],
            "modified": "9999-12-31T00:00:00.000Z",
            "name": "Incident on Port",
            "pattern": "[unconverted_term:NCCIC:Observable-d2be7dd8-0b0c-4c76-8bc0-20c93718941c]",
            "spec_version": "2.1",
            "type": "indicator",
            "valid_from": "9999-12-31T00:00:00.000000Z"
        }
    ],
    "type": "bundle"
}

**Comment by clenk** [comment]
Should be fixed by b10c10a.
