### ISSUE TITLE
Cybox Title, Description, Keywords are not translated to JSON

### ISSUE THREAD

**Issue by hanymorcos** [oasis-open/cti-stix-elevator#155]
The following elements are not translated over to JSON. 

```xml
<indicator:Observable id="ob-08-1">
	<cybox:Title>
		TEST23237
	</cybox:Title>
	<cybox:Description>
		TEST23238
	</cybox:Description>
	<cybox:Keywords>
		<cybox:Keyword>TEST23239</cybox:Keyword>
	</cybox:Keywords>
	<cybox:Object id="obj-08-1">
		<cybox:Properties xsi:type="AddressObj:AddressObjectType" category="ipv4-addr" is_source="false" is_destination="true" is_spoofed="false">
			<AddressObj:Address_Value>5.50.50.10</AddressObj:Address_Value>
		</cybox:Properties>
		<cybox:Related_Objects>
			<cybox:Related_Object id="rel-obj-08-1">
				<cybox:Properties xsi:type="AddressObj:AddressObjectType" category="ipv4-addr" is_source="false" is_destination="true" is_spoofed="false">
					<AddressObj:Address_Value>5.50.50.11</AddressObj:Address_Value>
				</cybox:Properties>
				<cybox:Relationship>
xsi:type="cyboxVocabs:ObjectRelationshipVocab-1.1">Redirects_To</cybox:Relationship>
			</cybox:Related_Object>
		</cybox:Related_Objects>
	</cybox:Object>
</indicator:Observable>
```

**Comment by rpiazza** [comment]
@hanymorcos, these properties cannot be represented in STIX 2.x.  This was a specific design decision in STIX 2.0, because Observed_Data are just facts - and need no extra information.
This is a problem for the elevator, which usually stores such properties on the description property of an SDO.

Once again, a warning would have been useful.

**Comment by hanymorcos** [comment]
Thanks Rich. 
I'm going through an example to validate the AIS Submission test case. You are correct some of the fields I was testing were not required for AIS submission.

https://www.us-cert.gov/sites/default/files/ais_files/AIS_Submission_Guidance_Appendix_A.pdf

**Comment by rpiazza** [comment]
Please reopen if necessary
