### ISSUE TITLE
Please tell me when a new release version will be published.

### ISSUE THREAD

**Issue by stmtstk** [oasis-open/cti-stix-elevator#165]
Hi,

I found that a TLP object which was converted by this library is invalid.
And I also found this issue was fixed as #146 .
But I could not pull this version by pip command because this issue is not published as a latest release.

So, if you know when the latest release version is released, please let me know.

Thanks!

**Comment by rpiazza** [comment]
It should be fairly soon.  We are currently updating many of the utilities to work with the latest working draft of the 2.1 specification.  An announcement will be sent to the cti mailing list when it is released.

**Comment by stmtstk** [comment]
OK. I got it. Thanks for your kindly reply.
I am looking forward to release this version.
