### ISSUE TITLE
Package build fails on windows due to encoding error

### ISSUE THREAD

**Issue by chisholm** [oasis-open/cti-stix-elevator#172]
Error for an 'sdist' invocation looks like:

```
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    readme = f.read()
  File "C:\Programming\python\stix\venv\maec2stix_py3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 725: character maps to <undefined>
```

The error is caused by utf-8 encoding in `README.rst`.  No encoding is specified in `setup.py` when the file is opened.  On Windows it defaults to cp1252, which fails to decode the file.  The problem characters are curly quotes around "best effort".

**Comment by rpiazza** [comment]
@chisholm,

I'm confused why this should have an impact on the maec converter - does it use the elevator??

**Comment by chisholm** [comment]
Yes, the "stepper".  MAEC 5 has STIX 2.0 SCOs; they needed to be upgraded to 2.1.  Chris pointed me to the work you did for that.

**Comment by rpiazza** [comment]
Just pushed a fix to master.
