### ISSUE TITLE
The disable/enable option are not handled correctly.

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-elevator#194]
The use case is: programmatically enable/disable messages at any time.

Because of the way the enable/disable option works, using set_option_value will not work as expected
A user would have to know that the “real” option is disabled, not disable

There also seems to be an issue with the processing of the enable/disable option.  They are strings from the command line, but CHECK_CODES has integers.

**Comment by emmanvg** [comment]
closed by #195
