### ISSUE TITLE
Handle orphaned observables

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-elevator#206]
See PR #205 for details.

**Comment by rpiazza** [comment]
If an observable contains an observable composition, it should be contained within an indicator, because it improbable that it is an actual observed fact.   The exception is if it referred to in an indicator via and idref.

**Comment by rpiazza** [comment]
Also to fix problem related to PR #205

**Comment by emmanvg** [comment]
closed by #209
