### ISSUE TITLE
LM Cyber Kill Chain conversion

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-stix-elevator#226]
LM Cyber Kill Chain has special requirements:

STIX 2.1 https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_i4tjv75ce50h
STIX 2.0 http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709267

stix has a [module ](https://github.com/STIXProject/python-stix/blob/master/stix/common/kill_chains/lmco.py)that could help which is based on this [guidance](https://stixproject.github.io/documentation/idioms/kill-chain/).

**Comment by rpiazza** [comment]
Also handle warning: "Unknown phase_id %s in %s" better
