### ISSUE TITLE
Text case issue-239.xml may need to be corrected

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-elevator#254]
Make sure PR #251 is merged into your work branch before working on this issue.

This test case has nested information sources - one at the package level and one in the marking definition.  They are both for CISA.  Neither has an id - so I'm not sure we can merge them into one - but something to explore?

On the other hand, I think the test case would be easier to follow if they were different.

**Comment by emmanvg** [comment]
fixed in #250
