### ISSUE TITLE
marking-definition object is getting removed on purpose ?

### ISSUE THREAD

**Issue by abhisheksachan** [oasis-open/cti-stix-elevator#266]
@rpiazza @emmanvg 
Hello guys
I am using stix-elevator lib to convert STIX1.x to STIX 2.1 format. While converting a XML package which contains `Marking_Structure` object inside a SDO(say campaign) is not getting mapped to SDO on conversion as `object_marking_refs`.
So i was debugging and found we are converting marking definition using convert_marking_specification() but in the end while we call finalize_bundle() we are on purpose removing objects which have `"definition_type" == "tlp"`

This piece of code removing the tlp objects inside finalize_bundle() 
`        if isinstance(value, (list, dict)):
            # Used to remove TLP markings from final bundle.
            if "definition_type" in value and value["definition_type"] == "tlp":
                to_remove.append(list(path))
            continue
`

Can you guys help me how should i proceed. are we not supporting marking-definition ?

**Comment by rpiazza** [comment]
Hi @abhisheksachan 

Yes this is done on purpose.  The STIX specification defines authoritarian objects for each TLP color.  Because they are defined within the specification, all tools that work with STIX must "know" those objects, so there is never a need to send them "over the wire".  This is an attempt to reduce the amount of "bytes" that need to be send.

Look in section 7.2 of the spec for those definitions.  You should see references to those objects in your elevator output.

**Comment by abhisheksachan** [comment]
@rpiazza 
I got your point, but when I am converting STIX 1.x to STIX 2.x, i am not getting `marking-definition` refrence under `object_marking_refs` field for a sdo


`<stix:STIX_Package 
	xmlns:tlpMarking="http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1"
	xmlns:campaign="http://stix.mitre.org/Campaign-1"
	xmlns:stix="http://stix.mitre.org/stix-1"
	xmlns:stixCommon="http://stix.mitre.org/common-1"
	xmlns:marking="http://data-marking.mitre.org/Marking-1"
	xmlns:example="http://example.com"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 id="example:Package-ee4312a3-ad08-440d-8d00-1272cdf4d60a" version="1.2">
    <stix:Campaigns>
        <stix:Campaign id="example:campaign-a679cb12-12ce-4873-80f1-9a510343e6cf" timestamp="2021-05-11T04:32:27.095427+00:00" xsi:type='campaign:CampaignType'>
            <campaign:Title>campaign title</campaign:Title>
            <campaign:Description>description related to Campaign</campaign:Description>
            <campaign:Short_Description>short_description related to Campaign</campaign:Short_Description>
            <campaign:Names>
                <campaign:Name>cam1</campaign:Name>
                <campaign:Name>cam2</campaign:Name>
            </campaign:Names>
            <campaign:Intended_Effect timestamp="2021-05-11T04:32:27.096301+00:00">
                <stixCommon:Value>Advantage - Economic</stixCommon:Value>
                <stixCommon:Description>intended effects description</stixCommon:Description>
                <stixCommon:Confidence timestamp="2021-05-11T04:32:27.096209+00:00">
                    <stixCommon:Value>Medium</stixCommon:Value>
                    <stixCommon:Description>confidence description</stixCommon:Description>
                </stixCommon:Confidence>
            </campaign:Intended_Effect>
            <campaign:Status>Historic</campaign:Status>
            <campaign:Activity>
                <stixCommon:Description ordinality="1">activity description</stixCommon:Description>
                <stixCommon:Description ordinality="2">activity description 2</stixCommon:Description>
            </campaign:Activity>
            <campaign:Activity>
                <stixCommon:Description ordinality="1">activity description 3</stixCommon:Description>
                <stixCommon:Description ordinality="2">activity description 4</stixCommon:Description>
            </campaign:Activity>
            <campaign:Handling>
                <marking:Marking>
                    <marking:Marking_Structure xsi:type='tlpMarking:TLPMarkingStructureType' color="AMBER"/>
                </marking:Marking>
            </campaign:Handling>
        </stix:Campaign>
    </stix:Campaigns>
</stix:STIX_Package>`

I am getting this as output 

`{
    "id": "bundle--ee4312a3-ad08-440d-8d00-1272cdf4d60a",
    "objects": [
        {
            "aliases": [
                "cam1",
                "cam2"
            ],
            "confidence": 50,
            "created": "2021-05-11T04:32:27.095Z",
            "description": "description related to Campaignshort_description related to Campaign\n\nINTENDED_EFFECT:Advantage - Economic: intended effects description\n\nINTENDED_EFFECT CONFIDENCE: Medium\n\tINTENDED_EFFECT DESCRIPTION: confidence description\n\nSTATUS:\n\tHistoric",
            "id": "campaign--a679cb12-12ce-4873-80f1-9a510343e6cf",
            "modified": "2021-05-11T04:32:27.095Z",
            "name": "campaign title",
            "spec_version": "2.1",
            "type": "campaign",
            "x_activity": "activity descriptionactivity description 2,activity description 3activity description 4",
            "x_status": "Historic"
        }
    ],
    "type": "bundle"
}`

**Comment by rpiazza** [comment]
Hi @abhisheksachan,

The STIX 1.x content didn't specify the data marking info completely.  There needs to be a marking and a controlled_structure spec (where the marking applies).  So for an object marking you always need:

> <marking:Controlled_Structure>//node() | //@*</marking:Controlled_Structure>

Here is some documentation on data markings in STIX 1.x:  https://stixproject.github.io/documentation/concepts/data-markings/

Use this STIX 1.x content:

```
<stix:STIX_Package xmlns:tlpMarking="http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1"
                   xmlns:campaign="http://stix.mitre.org/Campaign-1" xmlns:stix="http://stix.mitre.org/stix-1"
                   xmlns:stixCommon="http://stix.mitre.org/common-1"
                   xmlns:marking="http://data-marking.mitre.org/Marking-1" xmlns:example="http://example.com"
                   xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   id="example:Package-ee4312a3-ad08-440d-8d00-1272cdf4d60a" version="1.2">
    <stix:Campaigns>
        <stix:Campaign id="example:campaign-a679cb12-12ce-4873-80f1-9a510343e6cf"
                       timestamp="2021-05-11T04:32:27.095427+00:00" xsi:type='campaign:CampaignType'>
            <campaign:Title>campaign title</campaign:Title>
            <campaign:Description>description related to Campaign</campaign:Description>
            <campaign:Short_Description>short_description related to Campaign</campaign:Short_Description>
            <campaign:Names>
                <campaign:Name>cam1</campaign:Name>
                <campaign:Name>cam2</campaign:Name>
            </campaign:Names>
            <campaign:Intended_Effect timestamp="2021-05-11T04:32:27.096301+00:00">
                <stixCommon:Value>Advantage - Economic</stixCommon:Value>
                <stixCommon:Description>intended effects description</stixCommon:Description>
                <stixCommon:Confidence timestamp="2021-05-11T04:32:27.096209+00:00">
                    <stixCommon:Value>Medium</stixCommon:Value>
                    <stixCommon:Description>confidence description</stixCommon:Description>
                </stixCommon:Confidence>
            </campaign:Intended_Effect>
            <campaign:Status>Historic</campaign:Status>
            <campaign:Activity>
                <stixCommon:Description ordinality="1">activity description</stixCommon:Description>
                <stixCommon:Description ordinality="2">activity description 2</stixCommon:Description>
            </campaign:Activity>
            <campaign:Activity>
                <stixCommon:Description ordinality="1">activity description 3</stixCommon:Description>
                <stixCommon:Description ordinality="2">activity description 4</stixCommon:Description>
            </campaign:Activity>
            <campaign:Handling>
                <marking:Marking>
                    <marking:Controlled_Structure>//node() | //@*</marking:Controlled_Structure>
                    <marking:Marking_Structure xsi:type='tlpMarking:TLPMarkingStructureType' color="AMBER"/>
                </marking:Marking>
            </campaign:Handling>
        </stix:Campaign>
    </stix:Campaigns>
</stix:STIX_Package>
```
