### ISSUE TITLE
Implement remaining Cyber Observable Objects from AIS Profile

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-stix-elevator#4]
| AIS Objects | In 3.0 | Implementation Status |
| --- | --- | --- |
| Layer 4 Protocol Type | IANA | |
| Address | X | Yes|
| Domain Name | X  | Most |
| DNS Query | | | 
| Email Message | X  |  Some|
| File | X | Most |
| HTTP Session | | |
| Link | | |
| Mutex| X | Most |
| Network Connection | X | Most |
| Socket Address | | |  
| Hostname | | |
| Port | Integer | n/a |
| URI | X | Yes|
| Windows Registry Key | X | Most |

The status refers to the coverage of the AIS profile

**Comment by rpiazza** [comment]
Network Traffic is needed

**Comment by rpiazza** [comment]
AIS Profile:  https://www.us-cert.gov/sites/default/files/ais_files/AIS_Submission_Guidance_Appendix_A.pdf

**Comment by gtback** [comment]
This has been done.
