### ISSUE TITLE
stix2_elevator cmd line script works on STIX 1.2 file but elevator fails when used as a library.

### ISSUE THREAD

**Issue by awest1339** [oasis-open/cti-stix-elevator#46]
Code:
```python
import stix2elevator

results = stix2elevator.elevate_file('Mandiant_APT1_report.xml')
print(results)
```
Traceback:
```python
  File "/opt/venv_elevator/lib/python3.6/site-packages/stix2elevator/utils.py", line 21, in warn
    if options.msg_id_enabled(ecode):
  File "/opt/venv_elevator/lib/python3.6/site-packages/stix2elevator/options.py", line 137, in msg_id_enabled
    return msg_id in get_option_value("enabled")
TypeError: argument of type 'NoneType' is not iterable
```

* Python version == 3.6
* Stix 2 elevator version == 0.2.0
* STIX version of file being elevated == 1.2

**Comment by rpiazza** [comment]
try calling initialize_options (in options.py) before you call the elevate_file.

**Comment by awest1339** [comment]
That worked. Maybe update the README to reflect that extra step? Unless I missed that in the docs somewhere.

Thanks!

**Comment by rpiazza** [comment]
No - you didn't miss it.  I will add something to the README

**Comment by clenk** [comment]
In addition, perhaps ElevatorOptions should have a default "enabled" value so it doesn't throw this error.

**Comment by rpiazza** [comment]
It does, but you have to initialize the ElevatorOptions singleton first.

This should probably be something we redesign when we work on #47
