### ISSUE TITLE
RFI: Does cti-stix-elevator support Bulk Transformations?

### ISSUE THREAD

**Issue by packet-rat** [oasis-open/cti-stix-elevator#48]
Need to convert 1,000s of legacy STIX packages.  Is this supported OOTB or do we have to iterate through each with a wrapper?

**Comment by rpiazza** [comment]
Probably a wrapper - see scripts/xml_runner.py

**Comment by gtback** [comment]
If you want a one-to-one mapping from input legacy STIX to output STIX 2 files, a simple wrapper is the best approach. If you need something more complex (one-to-many or many-to-one), we would need to add something to the elevator.
