### ISSUE TITLE
Add 1.x properties missing from 2.0 to description

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-stix-elevator#6]
Most of this has been done, but a few fields still remain.

**Comment by rpiazza** [comment]
Hi - this is an annoying thing to check - but someone has to do it :-(

Just check to see if all properties not transferable to STIX 2.0 are either put into the description field or a message is printed "not handled yet".  Some of the unhandled properties are marked by TODOs - others aren't - you just have to compare to the STIX 1.x schema....
