### ISSUE TITLE
clear_pattern_mapping renamed but not all references updated

### ISSUE THREAD

**Issue by StephenThomson** [oasis-open/cti-stix-elevator#64]
clear_pattern_mapping has been renamed to clear_pattern_cache but the references in __init__.py @ 79 & 120 have not been updated.

**Comment by rpiazza** [comment]
Thanks for noting this.

**Comment by rpiazza** [comment]
Fixed in https://github.com/oasis-open/cti-stix-elevator/commit/c848c604138792451e199e407aae3c83464ca89e
