### ISSUE TITLE
Not all CybOX 2.x objects can be converted

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-elevator#69]
In version 1.0 of the elevator, we only implemented the conversion of a subset of the CybOX 2.x objects that could be represented in STIX 2.0.  This subset was informed by the DHS NCCIC AIS profile for STIX 1.x.

For instance, X509 Certificates and UserAccounts are not handled by the elevator.

**Comment by gtback** [comment]
Is this a duplicate of #50?

**Comment by rpiazza** [comment]
Duplicate of #50
