### ISSUE TITLE
Warning logging exceptions with certain commandline option combinations

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix-elevator#73]
Running the elevator CLI script with the options `-s -p strict_policy` gives the following error:

    No handlers could be found for logger "stix2elevator.options"

Running the elevator CLI script with the options `-s --message-log-directory <dir>` gives the following error:

      File "/home/lu/Projects/cti-stix-elevator/stix2elevator/options.py", line 87, in __init__
        warn("Both console and output log have disabled messages.", 209)
    NameError: global name 'warn' is not defined

I installed from master, not PyPI.

**Comment by emmanvg** [comment]
@clenk, I will look into this.
