### ISSUE TITLE
'- no identifying information available' for AISMarkingStructure

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix-elevator#79]
This is a usability thing, but I'm getting error messages like 

    [905] [WARNING] [2017-10-09 13:12:49,343] Timestamp not available for - no identifying information available, using current time

Is it possible for `identifying_info()` to look at the class or type? `Timestamp not available for AISMarkingDefinition, ...` would be more helpful.

**Comment by gtback** [comment]
If I remember, this code is not immediately able to tell the container it's in... but it's possible I'm confusing that with something else. @emmanvg ? @rpiazza ? Do you know?

**Comment by emmanvg** [comment]
That is correct. In addition, you may find STIX 1.X data in the wild that simply lack on information to properly identify `the` object that has properties missing. This change should be quick, but be aware that your mileage may vary depending on the object that lack identifying information.
