### ISSUE TITLE
Campaign Alias handling bug

### ISSUE THREAD

**Issue by cobsec** [oasis-open/cti-stix-elevator#91]
Hey all - seems to be a bug with converting campaign entities that have aliases / names from 1 to 2. TypeError raised:
<img width="1016" alt="screen shot 2017-12-08 at 11 05 27" src="https://user-images.githubusercontent.com/16275379/33761019-031caad6-dc08-11e7-8d36-39eddacb8e05.png">
<img width="1631" alt="screen shot 2017-12-08 at 11 06 56" src="https://user-images.githubusercontent.com/16275379/33761039-1625e764-dc08-11e7-9919-14d5e45ff6f1.png">

You can see that an object is trying to be string'd rather than the value so can't get json serialised. I had a play and think I found the problem:

```
def convert_campaign(camp, bundle_instance, parent_created_by_ref, parent_timestamp):
    campaign_instance = create_basic_object("campaign", camp, parent_timestamp)
    process_description_and_short_description(campaign_instance, camp)
    campaign_instance["name"] = camp.title
    if camp.names is not None:
        campaign_instance["aliases"] = []
        for name in camp.names:
            campaign_instance["aliases"].append(name)
    # process information source before any relationships
```

`append(name)` should read `append(name.value)` I think?

Making the change seems to work for my test case:
<img width="1626" alt="screen shot 2017-12-08 at 11 11 24" src="https://user-images.githubusercontent.com/16275379/33761235-9247c830-dc08-11e7-8701-4586982170c7.png">

**Comment by gtback** [comment]
Thanks for opening this, @cobsec  and sorry for not seeing it right away. I'll hopefully have a chance to look at it soon.
